### ISSUE TITLE
How can we visualize the images?

### ISSUE THREAD

**Issue by manish2295** [ssfootball04/generative_pose#1]
How to visualize the images using viz.py file?

**Comment by saurabhsharma1993** [comment]
Please use the respective apis for 2d and 3d pose.

**Comment by PanJinquan** [comment]
Hi ,How to use the 2d or 3d pose  API to visualize in images.
`show3Dpose(title, channels_pred, add_labels=False)`or `show2Dpose(title, channels_pred, lcolor="xkcd:darkblue", rcolor="xkcd:crimson", add_labels=False)`?

**Comment by saurabhsharma1993** [comment]
hi, you can use show3Dpose for the 3D pose viz and show2Dpose for the 2d pose viz
