### ISSUE TITLE
Why do you generate and score the multi-pose

### ISSUE THREAD

**Issue by gh18l** [ssfootball04/generative_pose#2]
Hello! I wonder whether you have ever tried generating the best 3D pose according to the ordinal score map directly? And Why not score the 3D pose according to the distance between prediction and GT with generated multi-pose directly?

**Comment by ssfootball04** [comment]
Hi,
_I wonder whether you have ever tried generating the best 3D pose according to the ordinal score map directly?_
-> If I understand correctly, your question is why don't we simply use the generated 3D pose that gets assigned the highest score by the Ordinal Scoring function (4). This is sub-optimal as the regressed ordinal relations are noisy, therefore we use the softmax weighted average.

 _And Why not score the 3D pose according to the distance between prediction and GT with generated multi-pose directly?_
-> G.T pose cannot be used during testing. However, we show the upper-bound performance using GT poses as an Oracle for scoring.

**Comment by saurabhsharma1993** [comment]
_I wonder whether you have ever tried generating the best 3D pose according to the ordinal score map directly?_
-> If I understand correctly, your question is why don't we simply use the generated 3D pose that gets assigned the highest score by the Ordinal Scoring function (4). This is sub-optimal as the regressed ordinal relations are noisy, therefore we use the softmax weighted average.

_And Why not score the 3D pose according to the distance between prediction and GT with generated multi-pose directly?_
-> G.T pose cannot be used during testing. However, we show the upper-bound performance using GT poses for scoring inside the Oracle.
