### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by lvandoit** [ssfootball04/generative_pose#3]
hi:
  When I finished training the network and tested it on the test data set, I found that the result was very different from that in the paper, and I did not change any parameters of the source code，So what's the reason? @ssfootball04

**Comment by saurabhsharma1993** [comment]
Can you please be specific, provide details on what you ran, the outputs you got after running the code ?
Thanks,
Saurabh

**Comment by lvandoit** [comment]
When training the network, the error is relatively small, while when the trained model is tested on the test data set, the error is becoming large @ssfootball04

**Comment by lvandoit** [comment]
Much worse than the results in the paper @ssfootball04

**Comment by saurabhsharma1993** [comment]
Please share commands and output, this information is very vague and unhelpful.
