### ISSUE TITLE
about pretrained model

### ISSUE THREAD

**Issue by amrbenattia** [ssfootball04/generative_pose#4]
Thanks for great work
I run the following line:
python main.py --exp example--test --numSamples 10 --load 'best_model.pth.pt'

the results are all numbers. and results/test folder was created but empty, is there any visualization such as images with 3d pose estimation

**Comment by saurabhsharma1993** [comment]
Hi,
The visualisation APIs are in src/viz.py; you are welcome to use them for your analysis.
