### ISSUE TITLE
Training Details

### ISSUE THREAD

**Issue by zhangyahu1** [ssfootball04/generative_pose#5]
Thanks for sharing your work!

I have a question about your training details. Do you use CMU Mocap dataset to trian your model when using 2D-3D paired data for evaluation?

**Comment by saurabhsharma1993** [comment]
Hi, no we don't use any CMU mocap in the paired setting, data for training comes only from the base dataset. Sorry for the late reply.

**Comment by zhangyahu1** [comment]
Thanks for your answer!
