### ISSUE TITLE
What's the meaning of oracle?

### ISSUE THREAD

**Issue by OOF-dura** [ssfootball04/generative_pose#8]
May I ask a silly quetsion... What's the meaning of oracle?

My understanding of oracle-based pose sample is that, for the output of CVAE, you will select the one which has the nearest distance to the GT data. 
![image](https://user-images.githubusercontent.com/22954901/125728426-36cd122b-3c91-4101-a3f3-1ccc18b29ae7.png)
But why do you call this **using an Oracle that has access to P_{3D}**?
Can we do this during test time (I mean a real-world scene, no 3D gt data)?

**Comment by saurabhsharma1993** [comment]
Hi, sorry for the late reply.
Here is the defn. of "oracle" from Merriam-Webster: a person or thing regarded as an infallible authority or guide on something. We have used this word in that sense. The Oracle evaluation is just a way to test the performance limits of the model. In a real-world scene we of course don't have access to any ground truth data.

**Comment by OOF-dura** [comment]
> Hi, sorry for the late reply.
> Here is the defn. of "oracle" from Merriam-Webster: a person or thing regarded as an infallible authority or guide on something. We have used this word in that sense. The Oracle evaluation is just a way to test the performance limits of the model. In a real-world scene we of course don't have access to any ground truth data.

Thank you for your kind reply!
Best,
Frank
